name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker Image
      run: |
        docker build -t my-tomcat-app .
      working-directory: ./path/to/your/app  # Replace with your application's directory

    - name: Tag Docker Image
      run: |
        docker tag my-tomcat-app <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/my-tomcat-app:latest
      env:
        YOUR_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Push Docker Image to ECR
      run: |
        docker push <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/my-tomcat-app:latest
      env:
        YOUR_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
