name: Java Web App CI/CD

on:
  push:
    branches:
      - main  # You can specify your main branch here

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload artifacts to AWS S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # Replace with your desired AWS region


    - name: Build with Maven
      run: | 
        #mvn clean package  # Adjust your build command as needed
        ls
        pwd
        cd CrudDemoWithMySql
        mvn --version
        mvn clean
        mvn install
        cd target
        ls
        aws s3 cp CrudDemoWithMySql-0.0.1-SNAPSHOT.war s3://ctl-crud-demo-build/

    - name: Create Docker Build and Upload to ECR 
      run: | 
        aws s3 cp s3://ctl-crud-demo-build/CrudDemoWithMySql-0.0.1-SNAPSHOT.war ./
        mv CrudDemoWithMySql-0.0.1-SNAPSHOT.war CrudDemoWithMySql.war
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s3c4l2m0
        docker build -t ctl-crud-demo .
        docker tag ctl-crud-demo:latest public.ecr.aws/s3c4l2m0/ctl-crud-demo:latest
        docker push public.ecr.aws/s3c4l2m0/ctl-crud-demo:latest
    
