name: Java CI/CD with AWS S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can change this to your required Java version

    - name: Build with Maven
      run: mvn clean package  # Replace with your Maven build command

    - name: Upload to AWS S3
      uses: jakejarvis/s3-sync-action@v0.3.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Replace with your desired AWS region
        source-dir: 'target/'  # Replace with the directory containing your artifacts
        dest-bucket: 'your-s3-bucket-name'  # Replace with your AWS S3 bucket name
        dest-dir: 'your-destination-directory'  # Replace with your desired S3 destination directory
